name: capturing information
on: [ push, workflow_dispatch ]
jobs:
  buil-info:
    runs-on: ubuntu-latest
    steps:
      - name: github context details
        run: |
          echo "=========GITHUB-CONTEXT========="
          echo "${{ toJson(github)}}"